# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('genre', models.CharField(choices=[('comedy', 'Komoedie'), ('horror', 'Horror')], max_length=100)),
                ('ort', models.CharField(max_length=200)),
                ('qual', models.CharField(choices=[('sehr gut', 'Sehr gut'), ('gut', 'Gut'), ('mittel', 'Mittel'), ('schlecht', 'Schlecht')], max_length=100)),
            ],
        ),
    ]
