# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verwaltung', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(choices=[('Komoedie', 'Komoedie'), ('Horror', 'Horror')], max_length=100),
        ),
        migrations.AlterField(
            model_name='film',
            name='qual',
            field=models.CharField(choices=[('sehr gut', 'sehr gut'), ('gut', 'gut'), ('mittel', 'mittel'), ('schlecht', 'schlecht')], max_length=100),
        ),
    ]
