# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verwaltung', '0003_auto_20171228_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='title',
            new_name='titel',
        ),
    ]
