# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verwaltung', '0005_auto_20171228_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='qual',
            field=models.CharField(blank=True, choices=[('sehr gut', 'sehr gut'), ('gut', 'gut'), ('mittel', 'mittel'), ('schlecht', 'schlecht')], max_length=100, null=True),
        ),
    ]
