# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verwaltung', '0006_auto_20171229_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='bew',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Keine', max_length=100),
        ),
    ]
