# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verwaltung', '0008_auto_20171229_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='bew',
            field=models.CharField(choices=[('-----', 'Keine'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Keine', max_length=100),
        ),
        migrations.AlterField(
            model_name='film',
            name='qual',
            field=models.CharField(choices=[('-----', 'Kein Eintrag'), ('sehr gut', 'sehr gut'), ('gut', 'gut'), ('mittel', 'mittel'), ('schlecht', 'schlecht')], default='Kein Eintrag', max_length=100),
        ),
    ]
